### ISSUE TITLE
Colors are slightly off between window frame and code background

### ISSUE THREAD

**Issue by dersimn** [Jax0rz/macOS-Dark#1]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/3258452/52519833-d1833e80-2c61-11e9-8817-5a36c23050fa.png">

**Comment by Jax0rz** [comment]
Sorry ,I've update it with my latest theme. I changed the color scheme to Dracula,please update it .
<img width="1392" alt="demo" src="https://user-images.githubusercontent.com/7557357/52546445-45f0e580-2dfa-11e9-880c-a27f72a1ea7d.png">
